AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
Rails:
  Enabled: true

StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'spec/spec_helper.rb'
